### ISSUE TITLE
Clients who have never gone from RR to CCC (recidivated) are in the database

### ISSUE THREAD

**Issue by kwarkster** [harrisms2/dataish#1]
These are clients who did at one point experience Rapid Rehousing, but shouldn't be included here because they never recidivated back into the CCC Point of Entry.  See clients 360, 1387, 957, etc.

**Comment by harrisms2** [comment]
The final DataFrame in the current code will include them so you can count how many times someone did NOT recidivate. We can make a recidivated DF by excluding the rows where entry_cc < 1971 (January 1, 1970 is used as the "start of time" or null value right now).

**Comment by kwarkster** [comment]
Gotcha.
